---
- name: Install Assault Cube
  hosts: gameserver
  vars_files:
    - vault.yml
  tasks:
    - name: Install a list of packages
      ansible.builtin.apt:
        pkg:
          - libsdl1.2debian
          - libsdl-image1.2
          - zlib1g
          - libogg0
          - libvorbis0a
          - libopenal1
          - libcurl4
          - tar
          - unzip
          - bzip2
        update_cache: true

    - name: Unarchive a file that needs to be downloaded (added in 2.0)
      ansible.builtin.unarchive:
        src: https://github.com/assaultcube/AC/releases/download/v1.2.0.2/AssaultCube_v1.2.0.2.tar.bz2
        dest: /opt
        remote_src: true
